package ic2_120.content.sync

import ic2_120.content.TickLimitedSidedEnergyContainer
import ic2_120.content.syncs.SyncSchema
import net.minecraft.util.math.Direction

/**
 * 创造模式发电机的同步属性与能量存储。
 * 无限生成能量（32 EU/t），无燃料消耗。
 */
class CreativeGeneratorSync(
    schema: SyncSchema,
    private val getFacing: () -> Direction,
    private val currentTickProvider: () -> Long? = { null }
) : TickLimitedSidedEnergyContainer(
    baseCapacity = ENERGY_CAPACITY,
    maxInsertPerTick = 0L,
    maxExtractPerTick = MAX_EXTRACT,
    currentTickProvider = currentTickProvider
) {

    companion object {
        /** 能量缓存容量 100,000 EU */
        const val ENERGY_CAPACITY = 100_000L
        /** 每 tick 最大输出 32 EU/t（与能量等级 1 对齐） */
        const val MAX_EXTRACT = 32L
        /** 每 tick 生成 32 EU */
        const val GENERATION_RATE = 32L
        const val NBT_ENERGY_STORED = "EnergyStored"
        const val NBT_TOTAL_GENERATED = "TotalGenerated"
    }

    var energy by schema.int("Energy")
    /** 累计总发电量（EU），用于 UI 显示 */
    var totalGenerated by schema.int("TotalGenerated", default = 0)
    private val flow = EnergyFlowSync(schema, this, useGeneratedAsInput = true)

    override fun getSideMaxInsert(side: Direction?): Long = 0L

    /** 正面不输出；其余面可输出，整机总输出由基类限制为 MAX_EXTRACT/tick */
    override fun getSideMaxExtract(side: Direction?): Long =
        if (side != getFacing()) MAX_EXTRACT else 0L

    override fun onEnergyCommitted() {
        energy = amount.toInt().coerceIn(0, Int.MAX_VALUE)
    }

    /**
     * 在 tick 结束时调用，同步当前 tick 的实际输出
     */
    fun syncCurrentTickFlow() {
        flow.syncCurrentTickFlow()
    }

    /** 获取同步的发电速度（EU/t） */
    fun getSyncedInsertedAmount(): Long = flow.getSyncedInsertedAmount()

    /** 获取同步的输出速度（EU/t） */
    fun getSyncedExtractedAmount(): Long = flow.getSyncedExtractedAmount()

    /** 获取累计总发电量 */
    fun getTotalGenerated(): Long = totalGenerated.toLong()

    /**
     * 更新累计发电量
     */
    fun addGenerated(amount: Long) {
        if (amount <= 0) return
        // 防止 Int 溢出
        val newTotal = (totalGenerated.toLong() + amount).coerceIn(0L, Int.MAX_VALUE.toLong())
        totalGenerated = newTotal.toInt()
    }
}
