package ic2_120.content.sync

import ic2_120.content.syncs.SyncSchema

class RtHeatGeneratorSync(
    schema: SyncSchema,
    private val heatFlow: HeatFlowSync? = null
) {
    /** 当前 tick 发热值（HU/t），由 BE 直接写入 */
    var heatGenerated by schema.int("HeatGenerated")

    /** 获取同步的滤波后产热速率（HU/t） */
    fun getSyncedGeneratedHeat(): Long = heatGenerated.toLong().coerceAtLeast(0L)

    /** 获取同步的滤波后输出速率（HU/t） */
    fun getSyncedOutputHeat(): Long = heatFlow?.getSyncedOutputHeat() ?: 0L
}
